CREATE TABLE IF NOT EXISTS Item
(
id int(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(63) NOT NULL,
imgPath VARCHAR(100) NOT NULL,
dateFound DATE NOT NULL,
timeFound TIME NOT NULL,
locationFound VARCHAR(63) NOT NULL,
description VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);